
import { Lemma } from './types';

export const LOCAL_STORAGE_KEYS = {
    USERS: 'MATCANBAN_USERS',
    PROMPTS: 'MATCANBAN_PROMPTS',
    CUSTOM_VOCAB: 'MATCANBAN_CUSTOM_VOCAB',
    PRACTICE_TESTS: 'MATCANBAN_PRACTICE_TESTS',
    PRACTICE_TESTS_LISTS: 'MATCANBAN_PRACTICE_TESTS_LISTS',
    GRAMMAR_UNITS: 'MATCANBAN_GRAMMAR_UNITS',
    GRAMMAR_GROUPS: 'MATCANBAN_GRAMMAR_GROUPS',
    GRAMMAR_VOCAB: 'MATCANBAN_GRAMMAR_VOCAB',

    // --- LEGACY / BASE KEYS ---
    WRITING_DATA: 'MATCANBAN_WRITING_DATA', // For base categories
    TIPS_DATA: 'MATCANBAN_TIPS_DATA', // For AIO/ContentService

    // --- NEW MODULAR KEYS ---
    
    // Foundation & Scenarios
    WRITING_FOUNDATION_CONTENT: 'MATCANBAN_WRITING_FOUNDATION_CONTENT',
    SPEAKING_SCENARIOS_CONTENT: 'MATCANBAN_SPEAKING_SCENARIOS_CONTENT',

    // Tips
    TIPS_1_2: 'MATCANBAN_TIPS_1_2',
    TIPS_3_4: 'MATCANBAN_TIPS_3_4',
    TIPS_5_6: 'MATCANBAN_TIPS_5_6',
    TIPS_7_8: 'MATCANBAN_TIPS_7_8',
    TIPS_9_10: 'MATCANBAN_TIPS_9_10',
    TIPS_11_30: 'MATCANBAN_TIPS_11_30',
    
    // VSTEP Speaking
    SPEAKING_VSTEP_P1_TASKS: 'MATCANBAN_SPEAKING_VSTEP_P1_TASKS',
    SPEAKING_VSTEP_P1_CONTENT: 'MATCANBAN_SPEAKING_VSTEP_P1_CONTENT',
    SPEAKING_VSTEP_P2_TASKS: 'MATCANBAN_SPEAKING_VSTEP_P2_TASKS',
    SPEAKING_VSTEP_P2_CONTENT: 'MATCANBAN_SPEAKING_VSTEP_P2_CONTENT',
    SPEAKING_VSTEP_P3_TASKS: 'MATCANBAN_SPEAKING_VSTEP_P3_TASKS',
    SPEAKING_VSTEP_P3_CONTENT: 'MATCANBAN_SPEAKING_VSTEP_P3_CONTENT',

    // VSTEP Writing
    VSTEP_WRITING_T1_SUBCATEGORIES: 'MATCANBAN_VSTEP_WRITING_T1_SUBCATEGORIES',
    VSTEP_WRITING_T1_CONTENT: 'MATCANBAN_VSTEP_WRITING_T1_CONTENT',
    VSTEP_WRITING_T2_SUBCATEGORIES: 'MATCANBAN_VSTEP_WRITING_T2_SUBCATEGORIES',
    VSTEP_WRITING_T2_CONTENT: 'MATCANBAN_VSTEP_WRITING_T2_CONTENT',

    // TOEIC Speaking
    SPEAKING_TOEIC_P1_TASKS: 'MATCANBAN_SPEAKING_TOEIC_P1_TASKS',
    SPEAKING_TOEIC_P1_CONTENT: 'MATCANBAN_SPEAKING_TOEIC_P1_CONTENT',
    SPEAKING_TOEIC_P2_TASKS: 'MATCANBAN_SPEAKING_TOEIC_P2_TASKS',
    SPEAKING_TOEIC_P2_CONTENT: 'MATCANBAN_SPEAKING_TOEIC_P2_CONTENT',
    SPEAKING_TOEIC_P3_TASKS: 'MATCANBAN_SPEAKING_TOEIC_P3_TASKS',
    SPEAKING_TOEIC_P3_CONTENT: 'MATCANBAN_SPEAKING_TOEIC_P3_CONTENT',
    SPEAKING_TOEIC_P4_TASKS: 'MATCANBAN_SPEAKING_TOEIC_P4_TASKS',
    SPEAKING_TOEIC_P4_CONTENT: 'MATCANBAN_SPEAKING_TOEIC_P4_CONTENT',
    SPEAKING_TOEIC_P5_TASKS: 'MATCANBAN_SPEAKING_TOEIC_P5_TASKS',
    SPEAKING_TOEIC_P5_CONTENT: 'MATCANBAN_SPEAKING_TOEIC_P5_CONTENT',

    // TOEIC Writing
    TOEIC_WRITING_P1_SUBCATEGORIES: 'MATCANBAN_TOEIC_WRITING_P1_SUBCATEGORIES',
    TOEIC_WRITING_P1_CONTENT: 'MATCANBAN_TOEIC_WRITING_P1_CONTENT',
    TOEIC_WRITING_P2_SUBCATEGORIES: 'MATCANBAN_TOEIC_WRITING_P2_SUBCATEGORIES',
    TOEIC_WRITING_P2_CONTENT: 'MATCANBAN_TOEIC_WRITING_P2_CONTENT',
    TOEIC_WRITING_P3_SUBCATEGORIES: 'MATCANBAN_TOEIC_WRITING_P3_SUBCATEGORIES',
    TOEIC_WRITING_P3_CONTENT: 'MATCANBAN_TOEIC_WRITING_P3_CONTENT',

    // IELTS Speaking
    SPEAKING_IELTS_P1_TASKS: 'MATCANBAN_SPEAKING_IELTS_P1_TASKS',
    SPEAKING_IELTS_P1_CONTENT: 'MATCANBAN_SPEAKING_IELTS_P1_CONTENT',
    SPEAKING_IELTS_P2_TASKS: 'MATCANBAN_SPEAKING_IELTS_P2_TASKS',
    SPEAKING_IELTS_P2_CONTENT: 'MATCANBAN_SPEAKING_IELTS_P2_CONTENT',
    SPEAKING_IELTS_P3_TASKS: 'MATCANBAN_SPEAKING_IELTS_P3_TASKS',
    SPEAKING_IELTS_P3_CONTENT: 'MATCANBAN_SPEAKING_IELTS_P3_CONTENT',

    // IELTS Writing (granular)
    WRITING_IELTS_T1_LINE_TASKS: 'MATCANBAN_WRITING_IELTS_T1_LINE_TASKS',
    WRITING_IELTS_T1_LINE_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_LINE_CONTENT',
    WRITING_IELTS_T1_BAR_TASKS: 'MATCANBAN_WRITING_IELTS_T1_BAR_TASKS',
    WRITING_IELTS_T1_BAR_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_BAR_CONTENT',
    WRITING_IELTS_T1_PIE_TASKS: 'MATCANBAN_WRITING_IELTS_T1_PIE_TASKS',
    WRITING_IELTS_T1_PIE_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_PIE_CONTENT',
    WRITING_IELTS_T1_TABLE_TASKS: 'MATCANBAN_WRITING_IELTS_T1_TABLE_TASKS',
    WRITING_IELTS_T1_TABLE_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_TABLE_CONTENT',
    WRITING_IELTS_T1_PROCESS_TASKS: 'MATCANBAN_WRITING_IELTS_T1_PROCESS_TASKS',
    WRITING_IELTS_T1_PROCESS_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_PROCESS_CONTENT',
    WRITING_IELTS_T1_MAP_TASKS: 'MATCANBAN_WRITING_IELTS_T1_MAP_TASKS',
    WRITING_IELTS_T1_MAP_CONTENT: 'MATCANBAN_WRITING_IELTS_T1_MAP_CONTENT',
    WRITING_IELTS_T2_OPINION_TASKS: 'MATCANBAN_WRITING_IELTS_T2_OPINION_TASKS',
    WRITING_IELTS_T2_OPINION_CONTENT: 'MATCANBAN_WRITING_IELTS_T2_OPINION_CONTENT',
    WRITING_IELTS_T2_DISCUSSION_TASKS: 'MATCANBAN_WRITING_IELTS_T2_DISCUSSION_TASKS',
    WRITING_IELTS_T2_DISCUSSION_CONTENT: 'MATCANBAN_WRITING_IELTS_T2_DISCUSSION_CONTENT',
    WRITING_IELTS_T2_PROBLEMSOLUTION_TASKS: 'MATCANBAN_WRITING_IELTS_T2_PROBLEMSOLUTION_TASKS',
    WRITING_IELTS_T2_PROBLEMSOLUTION_CONTENT: 'MATCANBAN_WRITING_IELTS_T2_PROBLEMSOLUTION_CONTENT',
    WRITING_IELTS_T2_ADVDIS_TASKS: 'MATCANBAN_WRITING_IELTS_T2_ADVDIS_TASKS',
    WRITING_IELTS_T2_ADVDIS_CONTENT: 'MATCANBAN_WRITING_IELTS_T2_ADVDIS_CONTENT',

    // Cambridge Young Learners
    CAMBRIDGE_STARTERS_DATA: 'MATCANBAN_CAMBRIDGE_STARTERS_DATA',
    CAMBRIDGE_MOVERS_DATA: 'MATCANBAN_CAMBRIDGE_MOVERS_DATA',
    CAMBRIDGE_FLYERS_DATA: 'MATCANBAN_CAMBRIDGE_FLYERS_DATA',
};

export const INITIAL_LEMMA: Lemma = { 
    type: 'verb', 
    text: 'work', 
    base: 'work', 
    past: 'worked', 
    pp: 'worked', 
    ing: 'working', 
    vi: 'làm việc' 
};
