import { saveData, loadOrInitializeData } from './dataService';
import { FoundationTopic, WritingSeed, PracticeMode, Tip, CambridgeTest, CambridgeQuestion, ExamTask } from '../types';

type DataItem = FoundationTopic | WritingSeed | Tip | CambridgeTest | ExamTask;

/**
 * Appends new AI-generated practice exercises to an existing item in a dataset.
 * This function ensures that old data is preserved and new data is added cumulatively.
 *
 * @param storageKey The localStorage key for the dataset.
 * @param itemId The unique ID (or code) of the item to update.
 * @param practiceMode The specific practice mode (e.g., 'reorder', 'fill_blank') to add exercises to.
 * @param newExercises An array of new exercise objects generated by the AI.
 * @returns An object containing the count of new and total exercises for the updated mode.
 */
export const accumulatePracticeData = (
    storageKey: string,
    itemId: string,
    practiceMode: Exclude<PracticeMode, 'free_write'>,
    newExercises: any[]
): { newItemCount: number; totalItemCount: number } => {
    
    const allData: (FoundationTopic | WritingSeed)[] = loadOrInitializeData(storageKey, []);

    const itemIndex = allData.findIndex(item => ('code' in item ? item.code : item.id) === itemId);

    if (itemIndex === -1) {
        throw new Error(`Item with ID "${itemId}" not found in data source "${storageKey}".`);
    }

    const updatedAllData = JSON.parse(JSON.stringify(allData));
    const itemToUpdate = updatedAllData[itemIndex];

    if (!itemToUpdate.practice) {
        itemToUpdate.practice = {};
    }
    const practiceModeKey = practiceMode as keyof typeof itemToUpdate.practice;
    if (!itemToUpdate.practice[practiceModeKey]) {
        itemToUpdate.practice[practiceModeKey] = [];
    }

    const existingExercises = itemToUpdate.practice[practiceModeKey] || [];
    // Type assertion to handle the dynamic key
    (itemToUpdate.practice as any)[practiceModeKey] = [...existingExercises, ...newExercises];

    saveData(storageKey, updatedAllData);
    
    console.log(`Successfully added ${newExercises.length} exercises to '${itemId}' for mode '${practiceMode}'.`);

    return {
        newItemCount: newExercises.length,
        totalItemCount: (itemToUpdate.practice as any)[practiceModeKey].length,
    };
};


/**
 * A generic function to append new items to a list within a potentially nested data structure.
 * It's designed to be flexible for various data shapes in localStorage.
 *
 * @param storageKey - The key for the entire dataset in localStorage.
 * @param findKey - The key of the top-level property to search within (e.g., 'subcategories'). Can be null for flat arrays.
 * @param findValue - The value to match to find the parent object (e.g., a subcategory_id). Can be null for flat arrays.
 * @param targetListKey - The key of the list within the parent object to append to (e.g., 'seeds'). Can be null for flat arrays.
 * @param newItems - The array of new items to append.
 * @param primaryKey - The property name of the unique identifier in each item (e.g., 'id', 'code').
 * @returns An object with the count of new and total items.
 */
export const accumulateListData = (
    storageKey: string,
    findKey: string | null,
    findValue: string | null,
    targetListKey: string | null,
    newItems: any[],
    primaryKey: string
): { newItemCount: number; totalItemCount: number } => {
    
    let allData = loadOrInitializeData<any>(storageKey, []);

    let targetList;
    let parentObject = null;

    if (findKey && findValue && targetListKey) {
        // Nested structure (e.g., updating 'seeds' in a specific subcategory)
        parentObject = allData.find((item: any) => item[findKey] === findValue);
        if (!parentObject) {
            // A more complex search, e.g., finding a subcategory within a category
            for (const category of allData) {
                if(category.subcategories) {
                    const sub = category.subcategories.find((s:any) => s[findKey] === findValue);
                    if(sub) {
                        parentObject = sub;
                        break;
                    }
                }
            }
        }
        if(!parentObject) throw new Error(`Could not find parent object with ${findKey} = ${findValue}`);
        targetList = parentObject[targetListKey];
    } else {
        // Flat array structure
        targetList = allData;
    }

    if (!Array.isArray(targetList)) {
        throw new Error(`Target list for key "${targetListKey}" is not an array.`);
    }

    // Filter out duplicates based on the primary key
    const existingKeys = new Set(targetList.map((item: any) => item[primaryKey]));
    const uniqueNewItems = newItems.filter((newItem: any) => !existingKeys.has(newItem[primaryKey]));

    if (uniqueNewItems.length === 0) {
        return { newItemCount: 0, totalItemCount: targetList.length };
    }

    // Append unique new items
    if (parentObject && targetListKey) {
        parentObject[targetListKey] = [...targetList, ...uniqueNewItems];
    } else {
        allData = [...targetList, ...uniqueNewItems];
    }

    saveData(storageKey, allData);

    return {
        newItemCount: uniqueNewItems.length,
        totalItemCount: targetList.length + uniqueNewItems.length
    };
};